// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wommdzioaoymqgeemhll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvbW1kemlvYW95bXFnZWVtaGxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDYyNDEsImV4cCI6MjA3MDYyMjI0MX0.zAwu9cpiy5xRt4ZOqaCfI1V3FGzzxT9uhv2RM6JfNII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});